source 'http://rubygems.org'

gem 'rails', '3.0.7'

gem 'mysql2', '~> 0.2.7'
gem 'kaminari', '~> 0.12.4'
gem 'devise', '~> 1.2.1'
gem 'rubycas-client', '~> 2.2.1'
gem 'devise_cas_authenticatable', '1.0.0.alpha10'
gem 'declarative_authorization', '~> 0.5.2'

group :development, :test do
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'rspec-rails', '~> 2.6'
end

group :test do
  gem 'factory_girl_rails', '~> 1.2.0'
end
