#
# Application URLS
#

development:
  cas_url: "https://aztec.ncgr.org:7777"
  cas_validate: "https://aztec.ncgr.org:7777/proxyValidate"
  root_url: "aztec.ncgr.org:7650/"

production:
  cas_url: "https://cas.comparative-legumes.org"
  cas_validate: "https://cas.comparative-legumes.org:8020/proxyValidate"
  root_url: "comparative-legumes.org/"

test:
  cas_url: "https://aztec.ncgr.org:7777"
  cas_validate: "https://aztec.ncgr.org:7777/proxyValidate"
  root_url: "silicon.ncgr.org:7650/"

